//
// Created by liuhao on 2018/1/6.
//

#ifndef URHO3DCOPY_SCENEEVENTS_H
#define URHO3DCOPY_SCENEEVENTS_H

#include "../Core/Object.h"

namespace Urho3D
{
	URHO3D_EVENT(E_ATTRIBUTEANIMATIONADDED, AttributeAnimationAdded)
	{
		URHO3D_PARAM(P_OBJECTANIMATION, ObjectAnimation);
		URHO3D_PARAM(P_ATTRIBUTEANIMATIONNAME, AttributeAnimationName);
	}

	URHO3D_EVENT(E_ATTRIBUTEANIMATIONREMOVED, AttributeAnimationRemoved)
	{
		URHO3D_PARAM(P_OBJECTANIMATION, ObjectAnimation);
		URHO3D_PARAM(P_ATTRIBUTEANIMATIONNAME, AttributeAnimationName);
	}

	URHO3D_EVENT(E_ATTRIBUTEANIMATIONUPDATE, AttributeAnimationUpdate)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_TIMESTEP, TimeStep);
	}

	URHO3D_EVENT(E_NODEADDED, NodeAdded)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_PARENT, Parent);
		URHO3D_PARAM(P_NODE, Node);
	}

	URHO3D_EVENT(E_NODEREMOVED, NodeRemoved)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_PARENT, Parent);
		URHO3D_PARAM(P_NODE, Node);
	}

	URHO3D_EVENT(E_NODENAMECHANGED, NodeNameChanged)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
	}

	URHO3D_EVENT(E_TEMPORARYCHANGED, TemporaryChanged)
	{
		URHO3D_PARAM(P_SERIALIZABLE, Serializable);
	}

	URHO3D_EVENT(E_NODETAGADDED, NodeTagAdded)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
		URHO3D_PARAM(P_TAG, Tag);
	}

	URHO3D_EVENT(E_NODETAGREMOVED, NodeTagRemoved)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
		URHO3D_PARAM(P_TAG, Tag);
	}

	URHO3D_EVENT(E_COMPONENTADDED, ComponentAdded)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
		URHO3D_PARAM(P_COMPONENT, Component);
	}

	URHO3D_EVENT(E_COMPONENTREMOVED, ComponentRemoved)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
		URHO3D_PARAM(P_COMPONENT, Component);
	}

	URHO3D_EVENT(E_COMPONENTENABLEDCHANGED, ComponentEnabledChanged)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_NODE, Node);
		URHO3D_PARAM(P_COMPONENT, Component);
	}

	URHO3D_EVENT(E_COMPONENTCLONED, ComponentCloned)
	{
		URHO3D_PARAM(P_SCENE, Scene);
		URHO3D_PARAM(P_COMPONENT, Component);
		URHO3D_PARAM(P_CLONECOMPONENT, CloneComponent);
	}
}


#endif //URHO3DCOPY_SCENEEVENTS_H
